CRITICAL - 2022-01-20 02:18:34 --> strtolower(): Passing null to parameter #1 ($string) of type string is deprecated
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8192, 'strtolower(): P...', 'C:\\xampp\\htdocs...', 253)
#1 C:\xampp\htdocs\bpkad\system\Validation\FormatRules.php(253): strtolower(NULL)
#2 C:\xampp\htdocs\bpkad\system\HTTP\RequestTrait.php(151): CodeIgniter\Validation\FormatRules->valid_ip('::1')
#3 C:\xampp\htdocs\bpkad\system\Config\Services.php(570): CodeIgniter\HTTP\Request->getIPAddress()
#4 C:\xampp\htdocs\bpkad\system\Config\BaseService.php(248): CodeIgniter\Config\Services::session(Object(Config\App), false)
#5 C:\xampp\htdocs\bpkad\system\Config\BaseService.php(189): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#6 C:\xampp\htdocs\bpkad\system\Config\Services.php(563): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 C:\xampp\htdocs\bpkad\system\Config\BaseService.php(248): CodeIgniter\Config\Services::session()
#8 C:\xampp\htdocs\bpkad\system\Common.php(909): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\AuthenticationBase.php(134): session('logged_in')
#10 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#11 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Filters\LoginFilter.php(45): Myth\Auth\Authentication\LocalAuthenticator->check()
#12 C:\xampp\htdocs\bpkad\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#13 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->run('/', 'before')
#14 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#17 {main}
CRITICAL - 2022-01-20 02:20:19 --> strtolower(): Passing null to parameter #1 ($string) of type string is deprecated
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8192, 'strtolower(): P...', 'C:\\xampp\\htdocs...', 253)
#1 C:\xampp\htdocs\bpkad\system\Validation\FormatRules.php(253): strtolower(NULL)
#2 C:\xampp\htdocs\bpkad\system\HTTP\RequestTrait.php(151): CodeIgniter\Validation\FormatRules->valid_ip('::1')
#3 C:\xampp\htdocs\bpkad\system\Config\Services.php(570): CodeIgniter\HTTP\Request->getIPAddress()
#4 C:\xampp\htdocs\bpkad\system\Config\BaseService.php(248): CodeIgniter\Config\Services::session(Object(Config\App), false)
#5 C:\xampp\htdocs\bpkad\system\Config\BaseService.php(189): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#6 C:\xampp\htdocs\bpkad\system\Config\Services.php(563): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#7 C:\xampp\htdocs\bpkad\system\Config\BaseService.php(248): CodeIgniter\Config\Services::session()
#8 C:\xampp\htdocs\bpkad\system\Common.php(909): CodeIgniter\Config\BaseService::__callStatic('session', Array)
#9 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\AuthenticationBase.php(134): session('logged_in')
#10 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#11 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Filters\LoginFilter.php(45): Myth\Auth\Authentication\LocalAuthenticator->check()
#12 C:\xampp\htdocs\bpkad\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#13 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->run('/', 'before')
#14 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#16 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#17 {main}
CRITICAL - 2022-01-20 09:38:18 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\xampp\htdocs\bpkad\system\bootstrap.php(146): CodeIgniter\CodeIgniter->initialize()
#1 C:\xampp\htdocs\bpkad\spark(45): require('C:\\xampp\\htdocs...')
#2 {main}
CRITICAL - 2022-01-20 09:39:08 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\xampp\htdocs\bpkad\system\bootstrap.php(146): CodeIgniter\CodeIgniter->initialize()
#1 C:\xampp\htdocs\bpkad\spark(45): require('C:\\xampp\\htdocs...')
#2 {main}
ERROR - 2022-01-20 18:28:16 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-01-20 18:28:16 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\bpkad\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\bpkad\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\bpkad\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\bpkad\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#5 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Controllers\AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2022-01-20 18:28:16 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\bpkad\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\bpkad\app\Views\errors\html\error_exception.php(96): print_r(Object(Myth\Auth\Controllers\AuthController), true)
#2 C:\xampp\htdocs\bpkad\system\Debug\Exceptions.php(229): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\bpkad\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\bpkad\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-01-20 18:28:20 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-01-20 18:28:20 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\bpkad\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\bpkad\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\bpkad\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\bpkad\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#5 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Controllers\AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2022-01-20 18:28:20 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\bpkad\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\bpkad\app\Views\errors\html\error_exception.php(96): print_r(Object(Myth\Auth\Controllers\AuthController), true)
#2 C:\xampp\htdocs\bpkad\system\Debug\Exceptions.php(229): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\bpkad\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\bpkad\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-01-20 18:28:56 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-01-20 18:28:56 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\bpkad\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\bpkad\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\bpkad\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\bpkad\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#5 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Controllers\AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2022-01-20 18:28:56 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\bpkad\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\bpkad\app\Views\errors\html\error_exception.php(96): print_r(Object(Myth\Auth\Controllers\AuthController), true)
#2 C:\xampp\htdocs\bpkad\system\Debug\Exceptions.php(229): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\bpkad\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\bpkad\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-01-20 18:29:01 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-01-20 18:29:01 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\xampp\htdocs\bpkad\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\bpkad\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\bpkad\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\bpkad\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#4 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#5 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Controllers\AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2022-01-20 18:29:01 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\bpkad\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\bpkad\app\Views\errors\html\error_exception.php(96): print_r(Object(Myth\Auth\Controllers\AuthController), true)
#2 C:\xampp\htdocs\bpkad\system\Debug\Exceptions.php(229): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\bpkad\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\bpkad\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#6 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-20 19:49:49 --> Undefined variable: user
#0 C:\xampp\htdocs\bpkad\app\Views\admin\edit.php(14): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 14, Array)
#1 C:\xampp\htdocs\bpkad\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\bpkad\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\bpkad\system\Common.php(1097): CodeIgniter\View\View->render('admin/edit', Array, true)
#4 C:\xampp\htdocs\bpkad\app\Controllers\Admin.php(54): view('admin/edit', Array)
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): App\Controllers\Admin->edit('7')
#6 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-20 19:51:22 --> Undefined variable: user
#0 C:\xampp\htdocs\bpkad\app\Views\admin\edit.php(18): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 18, Array)
#1 C:\xampp\htdocs\bpkad\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\bpkad\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\bpkad\system\Common.php(1097): CodeIgniter\View\View->render('admin/edit', Array, true)
#4 C:\xampp\htdocs\bpkad\app\Controllers\Admin.php(54): view('admin/edit', Array)
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): App\Controllers\Admin->edit('7')
#6 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-20 20:04:02 --> Undefined variable: user
#0 C:\xampp\htdocs\bpkad\app\Views\admin\edit.php(15): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 15, Array)
#1 C:\xampp\htdocs\bpkad\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\bpkad\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\bpkad\system\Common.php(1097): CodeIgniter\View\View->render('admin/edit', Array, true)
#4 C:\xampp\htdocs\bpkad\app\Controllers\Admin.php(54): view('admin/edit', Array)
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): App\Controllers\Admin->edit('7')
#6 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-01-20 20:47:31 --> Table 'project1.user' doesn't exist
CRITICAL - 2022-01-20 20:47:31 --> Table 'project1.user' doesn't exist
#0 C:\xampp\htdocs\bpkad\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\bpkad\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\bpkad\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\bpkad\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\bpkad\system\Model.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\bpkad\system\BaseModel.php(523): CodeIgniter\Model->doFind(true, '7')
#6 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\AuthenticationBase.php(137): CodeIgniter\BaseModel->find('7')
#7 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(70): Myth\Auth\Authentication\AuthenticationBase->isLoggedIn()
#8 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Filters\LoginFilter.php(45): Myth\Auth\Authentication\LocalAuthenticator->check()
#9 C:\xampp\htdocs\bpkad\system\Filters\Filters.php(173): Myth\Auth\Filters\LoginFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#10 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->run('logout', 'before')
#11 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2022-01-20 20:48:12 --> Trying to get property 'password_hash' of non-object
#0 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(165): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 165, Array)
#1 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#2 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Controllers\AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#3 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptLogin()
#4 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-20 20:50:13 --> Trying to get property 'password_hash' of non-object
#0 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(165): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 165, Array)
#1 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#2 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Controllers\AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#3 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptLogin()
#4 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-20 20:50:25 --> Trying to get property 'password_hash' of non-object
#0 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(165): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 165, Array)
#1 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#2 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Controllers\AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#3 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptLogin()
#4 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-20 20:54:04 --> Trying to get property 'password_hash' of non-object
#0 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(165): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 165, Array)
#1 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#2 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Controllers\AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#3 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptLogin()
#4 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-20 20:54:22 --> Trying to get property 'password_hash' of non-object
#0 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(165): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 165, Array)
#1 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#2 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Controllers\AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#3 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptLogin()
#4 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-20 20:55:52 --> Trying to get property 'password_hash' of non-object
#0 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(165): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 165, Array)
#1 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#2 C:\xampp\htdocs\bpkad\vendor\myth\auth\src\Controllers\AuthController.php(88): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#3 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): Myth\Auth\Controllers\AuthController->attemptLogin()
#4 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-20 21:30:53 --> Trying to get property 'username' of non-object
#0 C:\xampp\htdocs\bpkad\app\Views\admin\edit.php(17): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 17, Array)
#1 C:\xampp\htdocs\bpkad\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\bpkad\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\bpkad\system\Common.php(1097): CodeIgniter\View\View->render('admin/edit', Array, true)
#4 C:\xampp\htdocs\bpkad\app\Controllers\Admin.php(59): view('admin/edit', Array)
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): App\Controllers\Admin->edit()
#6 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-20 21:31:56 --> Trying to get property 'username' of non-object
#0 C:\xampp\htdocs\bpkad\app\Views\admin\edit.php(17): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 17, Array)
#1 C:\xampp\htdocs\bpkad\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\bpkad\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\bpkad\system\Common.php(1097): CodeIgniter\View\View->render('admin/edit', Array, true)
#4 C:\xampp\htdocs\bpkad\app\Controllers\Admin.php(59): view('admin/edit', Array)
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): App\Controllers\Admin->edit()
#6 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-20 21:43:57 --> Trying to get property 'username' of non-object
#0 C:\xampp\htdocs\bpkad\app\Views\admin\edit.php(17): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 17, Array)
#1 C:\xampp\htdocs\bpkad\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\bpkad\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\bpkad\system\Common.php(1097): CodeIgniter\View\View->render('admin/edit', Array, true)
#4 C:\xampp\htdocs\bpkad\app\Controllers\Admin.php(59): view('admin/edit', Array)
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): App\Controllers\Admin->edit()
#6 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-20 21:48:50 --> Trying to get property 'userid' of non-object
#0 C:\xampp\htdocs\bpkad\app\Views\admin\detail.php(12): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 12, Array)
#1 C:\xampp\htdocs\bpkad\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\bpkad\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\bpkad\system\Common.php(1097): CodeIgniter\View\View->render('admin/detail', Array, true)
#4 C:\xampp\htdocs\bpkad\app\Controllers\Admin.php(59): view('admin/detail', Array)
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): App\Controllers\Admin->edit()
#6 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-20 21:51:54 --> Undefined variable: user
#0 C:\xampp\htdocs\bpkad\app\Views\admin\detail.php(12): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 12, Array)
#1 C:\xampp\htdocs\bpkad\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\bpkad\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\bpkad\system\Common.php(1097): CodeIgniter\View\View->render('admin/detail', Array, true)
#4 C:\xampp\htdocs\bpkad\app\Controllers\Admin.php(66): view('admin/detail')
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): App\Controllers\Admin->simpan_edit()
#6 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-20 21:53:16 --> Undefined variable: user
#0 C:\xampp\htdocs\bpkad\app\Views\admin\detail.php(12): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 12, Array)
#1 C:\xampp\htdocs\bpkad\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\bpkad\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\bpkad\system\Common.php(1097): CodeIgniter\View\View->render('admin/detail', Array, true)
#4 C:\xampp\htdocs\bpkad\app\Controllers\Admin.php(66): view('admin/detail')
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): App\Controllers\Admin->simpan_edit()
#6 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-20 21:53:48 --> Undefined variable: user
#0 C:\xampp\htdocs\bpkad\app\Views\admin\detail.php(12): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 12, Array)
#1 C:\xampp\htdocs\bpkad\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\bpkad\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\bpkad\system\Common.php(1097): CodeIgniter\View\View->render('admin/detail', Array, true)
#4 C:\xampp\htdocs\bpkad\app\Controllers\Admin.php(66): view('admin/detail')
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): App\Controllers\Admin->simpan_edit()
#6 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-20 21:54:41 --> Invalid file: admin.php
#0 C:\xampp\htdocs\bpkad\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('admin.php')
#1 C:\xampp\htdocs\bpkad\system\Common.php(1097): CodeIgniter\View\View->render('admin', Array, true)
#2 C:\xampp\htdocs\bpkad\app\Controllers\Admin.php(64): view('admin')
#3 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): App\Controllers\Admin->simpan_edit()
#4 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-20 21:55:01 --> Invalid file: admin/.php
#0 C:\xampp\htdocs\bpkad\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('admin/.php')
#1 C:\xampp\htdocs\bpkad\system\Common.php(1097): CodeIgniter\View\View->render('admin/', Array, true)
#2 C:\xampp\htdocs\bpkad\app\Controllers\Admin.php(64): view('admin/')
#3 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): App\Controllers\Admin->simpan_edit()
#4 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-20 21:55:11 --> Invalid file: admin/.php
#0 C:\xampp\htdocs\bpkad\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('admin/.php')
#1 C:\xampp\htdocs\bpkad\system\Common.php(1097): CodeIgniter\View\View->render('admin/', Array, true)
#2 C:\xampp\htdocs\bpkad\app\Controllers\Admin.php(64): view('admin/')
#3 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): App\Controllers\Admin->simpan_edit()
#4 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-20 21:57:40 --> Invalid file: /admin.php
#0 C:\xampp\htdocs\bpkad\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/admin.php')
#1 C:\xampp\htdocs\bpkad\system\Common.php(1097): CodeIgniter\View\View->render('/admin', Array, true)
#2 C:\xampp\htdocs\bpkad\app\Controllers\Admin.php(65): view('/admin')
#3 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(824): App\Controllers\Admin->simpan_edit()
#4 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#5 C:\xampp\htdocs\bpkad\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\bpkad\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\bpkad\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
